### ISSUE TITLE
Css variables won't parsed

### ISSUE THREAD

**Issue by NV4RE** [jonkemp/inline-css#125]
Hello, it seem css variable not supported in most email client, and it should be replace by inliner before sent.

input
```css
/* style.css */
.bg-gray-100{
  --tw-bg-opacity:1;
  background-color:rgb(237 242 247/var(--tw-bg-opacity));
}
```
```html
<!-- index.html -->
<link href="style.css" rel="stylesheet" />
<div class="bg-gray-100">
  Hello there
</div>
```

output
```html
<div class="bg-gray-100" style="--tw-bg-opacity: 1; background-color: rgb(237 242 247/var(--tw-bg-opacity));">
  Hello there
</div>
```

expected
```html
<div style="--tw-bg-opacity: 1; background-color: rgb(237 242 247/1);">
  Hello there
</div>
```
